// <auto-generated />
namespace Labs.WPF.TvShowOrganizer.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Updateerroronpropertyname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updateerroronpropertyname));
        
        string IMigrationMetadata.Id
        {
            get { return "201802182249151_Update error on property name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
