// <auto-generated />
namespace Labs.WPF.TvShowOrganizer.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NumberofEpisodesfield : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NumberofEpisodesfield));
        
        string IMigrationMetadata.Id
        {
            get { return "201803261720422_Number of Episodes field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
