// <auto-generated />
namespace Labs.WPF.TvShowOrganizer.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ServerTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ServerTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201802191455043_Server Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
